# This workflow will install Python dependencies and run tests with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Test

on: 
  push

jobs:
  test:
    name: ${{ matrix.os}} / py${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu, macOS]
        python_version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Install Python ${{ matrix.python_version }}
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64
          
      - name: Install (testing) requirements
        run: |
          python -m pip install --upgrade pip setuptools
          pip install pytest
      - name: Install psignifit to be tested
        run: |
          pip install .
      - name: Run tests for ${{ matrix.python_version }} through nox
        run: |
          pytest -vv    


